version: '3.4'

services:
  jupyter_lab_service:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: jupyter_lab_gabor
    container_name: gabor_lab 
    volumes:
      - /jupyter_lab_data:/home/jovyan/work
    ports:
      - 8888:8888
      - 1234:1234
    environment:
      - GRANT_SUDO=yes
    tty:  false
    network_mode: host
