version: '3.4'

services:
  jupyter_lab_service:
    build:
      context: .
      dockerfile: Dockerfile.with_proxy
      network: host
    image: jupyter_lab_gabor
    container_name: gabor_lab 
    volumes:
      - /jupyter_lab_data:/work
      - ./start.sh:/start.sh
    ports:
      - 8889:8889
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: always
    network_mode: host
    entrypoint:
      - /bin/bash
      - /start.sh
